

/*********************CREATE DATABASE********************************/

CREATE DATABASE SRM_PRO	
GO 
USE SRM_PRO



/************************ CREATE TABLE AUTHORITY *************************/
CREATE TABLE AUTHORITY(AUTHORITYID	VARCHAR(15)	NOT NULL,
							AUTHORITY_NAME	nvarchar(50)	NOT NULL)

--PRIMARY KEY
ALTER TABLE AUTHORITY
		ADD CONSTRAINT PK_AUTHORITY
			PRIMARY KEY (AUTHORITYID)
			

/************************ CREATE TABLE DEPARTMENT *************************/
CREATE TABLE DEPARTMENT(DEPARTMENTID	VARCHAR(15)	NOT NULL,
							DEPARTMENT_NAME	nvarchar(50)	NOT NULL,
								DEPARTMENT_STATUS BIT NOT NULL)

--PRIMARY KEY
ALTER TABLE DEPARTMENT
		ADD CONSTRAINT PK_DEPARTMENT
			PRIMARY KEY (DEPARTMENTID)
			

/************************ CREATE TABLE DEPARTMENT *************************/
CREATE TABLE DEPARTMENT_AUTHORITY(DEPARTMENTID VARCHAR(15)	NOT NULL,
									AUTHORITYID	VARCHAR(15)	NOT NULL)

--PRIMARY KEY
ALTER TABLE DEPARTMENT_AUTHORITY
		ADD CONSTRAINT PK_DEPARTMENT_AUTHORITY
			PRIMARY KEY (DEPARTMENTID, AUTHORITYID)
	
--REFERENCES KEY			
ALTER TABLE DEPARTMENT_AUTHORITY 
		ADD CONSTRAINT FK_DEPARTMENT_AUTHORITY_DEPARTMENT FOREIGN KEY (DEPARTMENTID)
			REFERENCES DEPARTMENT(DEPARTMENTID)
			
ALTER TABLE DEPARTMENT_AUTHORITY 
		ADD CONSTRAINT FK_DEPARTMENT_AUTHORITY_AUTHORITY FOREIGN KEY (AUTHORITYID)
			REFERENCES AUTHORITY(AUTHORITYID)			


/************************ CREATE TABLE USER  *************************/
			
CREATE TABLE [USER]([USERID]	VARCHAR(9) NOT NULL,
						NAME NVARCHAR(50) NOT NULL,
							[USER_DATEOFBIRTH] DATETIME NOT NULL,
								[USER_ADDRESS]	NVARCHAR(200)	NOT NULL,
									[USER_PHONE]	VARCHAR(15)NOT NULL,
										[USER_GENDER]	NVARCHAR(5)	NOT NULL,
											[PASSWORD]	VARCHAR(32)	NOT NULL,
												[USER_STATUS] BIT NOT NULL,
													[USER_LOGINALOWED]  BIT NOT NULL,
														DEPARTMENTID VARCHAR(15) NOT NULL,
															AUTHORITYID VARCHAR(15)	NOT NULL)
								
--PRIMARY KEY
ALTER TABLE [USER]
		ADD CONSTRAINT PK_USER
			PRIMARY KEY ([USERID])	
--REFERENCES KEY			
ALTER TABLE [USER] 
		ADD CONSTRAINT FK_USER_DEPARTMENT FOREIGN KEY (DEPARTMENTID)
			REFERENCES DEPARTMENT(DEPARTMENTID)
	
ALTER TABLE [USER] 
		ADD CONSTRAINT FK_USER_AUTHORITY FOREIGN KEY (AUTHORITYID)
			REFERENCES AUTHORITY(AUTHORITYID)

		
/************************ CREATE TABLE STUDENT  *************************/
CREATE TABLE STUDENT(STUDENTID	VARCHAR(9)	not null,
							STUDENT_NAME	NVARCHAR(50)	NOT NULL,
								BATCH INT NOT NULL,
									STUDENT_ADDRESS NVARCHAR(200)	NOT NULL,
										STUDENT_GENDER	NVARCHAR(5)	NOT NULL,
											STUDENT_DATEOFBIRTH DATETIME NOT NULL,
												DEPARTMENTID VARCHAR(15) NOT NULL,
													[USERID]	VARCHAR(9) NOT NULL )	

--PRIMARY KEY
ALTER TABLE STUDENT
		ADD CONSTRAINT PK_STUDENT
			PRIMARY KEY (STUDENTID)
			
--REFERENCES KEY
ALTER TABLE STUDENT 
		ADD CONSTRAINT FK_STUDENT_DEPARTMENT FOREIGN KEY (DEPARTMENTID)
			REFERENCES DEPARTMENT(DEPARTMENTID)
			
--REFERENCES KEY
ALTER TABLE STUDENT 
		ADD CONSTRAINT FK_STUDENT_USER FOREIGN KEY ([USERID])
			REFERENCES [USER]([USERID])

/************************ CREATE TABLE RECORD  *************************/
CREATE TABLE RECORD (RECORDID INT NOT NULL,
						RECORD_NAME NVARCHAR(150))

--PRIMARY KEY
ALTER TABLE RECORD
	ADD CONSTRAINT PK_RECORD
		PRIMARY KEY (RECORDID)

/************************ CREATE TABLE RECEIPT  *************************/
CREATE TABLE RECEIPT(RECEIPTID VARCHAR(10) NOT NULL,
						STUDENTID VARCHAR(9)NOT NULL,
							USERID VARCHAR(9) NOT NULL,
								DATE_CREATED DATETIME NOT NULL,
									RECEIPTIDTEMP VARCHAR(10) NULL,
										NUMBEROFUPDATE INT)

--PRIMARY KEY
ALTER TABLE RECEIPT
	ADD CONSTRAINT PK_RECEIPT
		PRIMARY KEY (RECEIPTID)

--REFERENCES KEY
ALTER TABLE RECEIPT 
		ADD CONSTRAINT FK_RECEIPT_STUDENT FOREIGN KEY (STUDENTID)
			REFERENCES STUDENT(STUDENTID)

--REFERENCES KEY
ALTER TABLE RECEIPT 
		ADD CONSTRAINT FK_RECEIPT_USER FOREIGN KEY (USERID)
			REFERENCES [USER](USERID)
			
/************************ CREATE TABLE RECEIPT DETAIL *************************/
CREATE TABLE RECEIPT_DETAIL(RECEIPTID VARCHAR(10) NOT NULL,
								RECORDID INT NOT NULL,
									RECORD_STATUS BIT NOT NULL,
										NOTE NVARCHAR(100) NOT NULL)
										--PRIMARY KEY
ALTER TABLE RECEIPT_DETAIL
	ADD CONSTRAINT PK_RECEIPT_DETAIL
		PRIMARY KEY (RECEIPTID, RECORDID)

--REFERENCES KEY
ALTER TABLE RECEIPT_DETAIL 
		ADD CONSTRAINT FK_RECEIPT_DETAIL_RECORD FOREIGN KEY (RECORDID)
			REFERENCES RECORD(RECORDID)
			
--REFERENCES KEY
ALTER TABLE RECEIPT_DETAIL 
		ADD CONSTRAINT FK_RECEIPT_DETAIL_RECEIPT FOREIGN KEY (RECEIPTID)
			REFERENCES RECEIPT(RECEIPTID)			
								
