

/*********************CREATE DATABASE********************************/

CREATE DATABASE SRM_PRO	
GO 
USE SRM_PRO



/************************ CREATE TABLE AUTHORITY *************************/
CREATE TABLE AUTHORITY(AUTHORITYID	VARCHAR(15)	NOT NULL,
							AUTHORITY_NAME	nvarchar(50)	NOT NULL)

--PRIMARY KEY
ALTER TABLE AUTHORITY
		ADD CONSTRAINT PK_AUTHORITY
			PRIMARY KEY (AUTHORITYID)
			

/************************ CREATE TABLE DEPARTMENT *************************/
CREATE TABLE DEPARTMENT(DEPARTMENTID	VARCHAR(15)	NOT NULL,
							DEPARTMENT_NAME	nvarchar(50)	NOT NULL,
								DEPARTMENT_STATUS BIT NOT NULL)

--PRIMARY KEY
ALTER TABLE DEPARTMENT
		ADD CONSTRAINT PK_DEPARTMENT
			PRIMARY KEY (DEPARTMENTID)
			

			
/************************ CREATE TABLE USER  *************************/
			
CREATE TABLE [USER]([USERID]	VARCHAR(9) NOT NULL,
						NAME NVARCHAR(50) NOT NULL,
							[USER_ADDRESS]	NVARCHAR(50)	NOT NULL,
								[USER_PHONE]	VARCHAR(15)NOT NULL,
									[USER_GENDER]	NVARCHAR(50)	NOT NULL,
										[PASSWORD]	VARCHAR(32)	NOT NULL,
											[USER_STATUS] BIT NOT NULL,
												[USER_LOGINALOWED]  BIT NOT NULL,
													DEPARTMENTID VARCHAR(15) NOT NULL,
														AUTHORITYID VARCHAR(15)	NOT NULL)
							
--PRIMARY KEY
ALTER TABLE [USER]
		ADD CONSTRAINT PK_USER
			PRIMARY KEY ([USERID])	
--REFERENCES KEY			
ALTER TABLE [USER] 
		ADD CONSTRAINT FK_USER_DEPARTMENT FOREIGN KEY (DEPARTMENTID)
			REFERENCES DEPARTMENT(DEPARTMENTID)
	
ALTER TABLE [USER] 
		ADD CONSTRAINT FK_USER_AUTHORITY FOREIGN KEY (AUTHORITYID)
			REFERENCES AUTHORITY(AUTHORITYID)
			
ALTER TABLE [USER]
DROP COLUMN USER_NAME
		
/************************ CREATE TABLE STUDENT  *************************/
CREATE TABLE STUDENT(STUDENTID	VARCHAR(9)	not null,
							STUDENT_NAME	NVARCHAR(50)	NOT NULL,
								STUDENT_ADDRESS NVARCHAR(50)	NOT NULL,
									STUDENT_PHONE	VARCHAR(15)NOT NULL,
										STUDENT_GENDER	NVARCHAR(50)	NOT NULL,
											STUDENT_DATEOFBIRTH DATETIME NOT NULL,
												RECORDSTATUS_ENROLLMENT_NOTICE BIT NOT NULL,
													RECORDSTATUS_HIGHSCHOLL_TRANSCRIPT BIT NOT NULL,
														RECORDSTATUS_BIRTH_CENTIFICATE BIT NOT NULL,
															RECORDSTATUS_ThePaperCentifyingObjectAndPriorityAreas  BIT NOT NULL,
																RECORDSTATUS_Matriculation_Profile  BIT NOT NULL,
																	RECORDSTATUS_Transfer_Activity_Profile  BIT NOT NULL,
																		RECORDSTATUS_4_STAMPED_ENVELOPE  BIT NOT NULL,
																			RECORDSTATUS_PHOTOGRAPHED  BIT NOT NULL,
																				DEPARTMENTID VARCHAR(15) NOT NULL,
																					[USERID]	VARCHAR(9) NOT NULL )	

--PRIMARY KEY
ALTER TABLE STUDENT
		ADD CONSTRAINT PK_STUDENT
			PRIMARY KEY (STUDENTID)
			
--REFERENCES KEY
ALTER TABLE STUDENT 
		ADD CONSTRAINT FK_STUDENT_DEPARTMENT FOREIGN KEY (DEPARTMENTID)
			REFERENCES DEPARTMENT(DEPARTMENTID)
			
--REFERENCES KEY
ALTER TABLE STUDENT 
		ADD CONSTRAINT FK_STUDENT_USER FOREIGN KEY ([USERID])
			REFERENCES [USER]([USERID])



